from typing import Final

#System main route
ROUTE_GENERAL: Final = "GENERAL"
ROUTE_FILE_REQUEST: Final = "FILE_REQUEST"
ROUTE_LEGAL_QUERY: Final = "LEGAL_QUERY"

TOP_LEVEL_ROUTES = frozenset([
    ROUTE_GENERAL,
    ROUTE_FILE_REQUEST,
    ROUTE_LEGAL_QUERY,
])

#Retriver route
LEGAL_ROUTE_REGULATION: Final = "REGULATION"
LEGAL_ROUTE_ORDER: Final = "ORDER"
LEGAL_ROUTE_GUIDELINE: Final = "GUIDELINE"
LEGAL_ROUTE_STANDARD: Final = "STANDARD"
LEGAL_ROUTE_GENERAL: Final = "GENERAL"

#Constant value
FUZZY_MATCH_THRESHOLD: Final = 65
DEFAULT_RETRIEVAL_K: Final = 3
HISTORY_WINDOW: Final = 5
LLM_TIMEOUT_SECONDS: Final = 30.0