CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Create USERS Table
-- ID is SERIAL (1, 2, 3...)
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password TEXT NOT NULL, 
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);